name: CI/CD - Build, Push & Deploy Infisical

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  BUILD_NUMBER: ${{ github.run_number }}
  EC2_IP: 15.156.219.253
  SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ca-central-1
  SECRET_ARN: arn:aws:secretsmanager:ca-central-1:659666453025:secret:infisical-secret-NGmqNX

jobs:
  build-and-push-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get secrets from AWS Secrets Manager
        id: secrets
        run: |
          SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id ${{ env.SECRET_ARN }} --query SecretString --output text)
          echo "POSTGRES_USER=$(echo $SECRET_JSON | jq -r '.POSTGRES_USER')" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=$(echo $SECRET_JSON | jq -r '.POSTGRES_PASSWORD')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Pull original images
        run: docker compose -f docker-compose.prod.yml pull
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}

      - name: Tag and push Backend image
        run: |
          docker tag infisical/infisical:latest-postgres ${{ env.DOCKER_USERNAME }}/infisical:latest
          docker tag infisical/infisical:latest-postgres ${{ env.DOCKER_USERNAME }}/infisical:${{ env.BUILD_NUMBER }}
          docker push ${{ env.DOCKER_USERNAME }}/infisical:latest
          docker push ${{ env.DOCKER_USERNAME }}/infisical:${{ env.BUILD_NUMBER }}

      - name: Tag and push Postgres image
        run: |
          docker tag postgres:14-alpine ${{ env.DOCKER_USERNAME }}/postgres:latest
          docker tag postgres:14-alpine ${{ env.DOCKER_USERNAME }}/postgres:${{ env.BUILD_NUMBER }}
          docker push ${{ env.DOCKER_USERNAME }}/postgres:latest
          docker push ${{ env.DOCKER_USERNAME }}/postgres:${{ env.BUILD_NUMBER }}

      - name: Tag and push Redis image
        run: |
          docker tag redis ${{ env.DOCKER_USERNAME }}/redis-image:latest
          docker tag redis ${{ env.DOCKER_USERNAME }}/redis-image:${{ env.BUILD_NUMBER }}
          docker push ${{ env.DOCKER_USERNAME }}/redis-image:latest
          docker push ${{ env.DOCKER_USERNAME }}/redis-image:${{ env.BUILD_NUMBER }}

  deploy:
    name: CD - Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push-db
    steps:
      - name: Install SSH Key for AWS EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to EC2 Instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
          # Become root
          sudo su -

          # Install dependencies
          apt-get update && apt-get install -y awscli jq docker.io

          # Export AWS credentials
          export AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
          export AWS_REGION=${{ env.AWS_REGION }}

          # Fetch secrets
          SECRET_JSON=\$(aws secretsmanager get-secret-value --secret-id ${{ env.SECRET_ARN }} --query SecretString --output text)

          ENCRYPTION_KEY=\$(echo "\$SECRET_JSON" | jq -r '.ENCRYPTION_KEY')
          AUTH_SECRET=\$(echo "\$SECRET_JSON" | jq -r '.AUTH_SECRET')
          POSTGRES_PASSWORD=\$(echo "\$SECRET_JSON" | jq -r '.POSTGRES_PASSWORD')
          POSTGRES_USER=\$(echo "\$SECRET_JSON" | jq -r '.POSTGRES_USER')
          POSTGRES_DB=\$(echo "\$SECRET_JSON" | jq -r '.POSTGRES_DB')
          SITE_URL=\$(echo "\$SECRET_JSON" | jq -r '.SITE_URL')

          # Write env file
          cat > /root/infisical.env << EOL
          ENCRYPTION_KEY=\$ENCRYPTION_KEY
          AUTH_SECRET=\$AUTH_SECRET
          POSTGRES_PASSWORD=\$POSTGRES_PASSWORD
          POSTGRES_USER=\$POSTGRES_USER
          POSTGRES_DB=\$POSTGRES_DB
          DB_CONNECTION_URI=postgres://\$POSTGRES_USER:\$POSTGRES_PASSWORD@infisical-db:5432/\$POSTGRES_DB
          REDIS_URL=redis://infisical-dev-redis:6379
          SITE_URL=\$SITE_URL
          EOL

          # Cleanup and prepare
          docker stop infisical-backend infisical-db infisical-dev-redis || true
          docker rm infisical-backend infisical-db infisical-dev-redis || true
          docker network create infisical-network || true
          docker volume create postgres_data || true

          # Pull new images
          docker pull ${{ env.DOCKER_USERNAME }}/infisical:latest
          docker pull ${{ env.DOCKER_USERNAME }}/postgres:latest
          docker pull ${{ env.DOCKER_USERNAME }}/redis-image:latest

          # Start containers
          docker run -d --name infisical-db \
            --network infisical-network \
            -p 5432:5432 \
            -v postgres_data:/var/lib/postgresql/data \
            -e POSTGRES_USER=\$POSTGRES_USER \
            -e POSTGRES_PASSWORD=\$POSTGRES_PASSWORD \
            -e POSTGRES_DB=\$POSTGRES_DB \
            ${{ env.DOCKER_USERNAME }}/postgres:latest

          sleep 10

          docker run -d --name infisical-dev-redis \
            --network infisical-network \
            -p 6379:6379 \
            ${{ env.DOCKER_USERNAME }}/redis-image:latest

          docker run -d --name infisical-backend \
            --network infisical-network \
            -p 80:8080 \
            --env-file /root/infisical.env \
            ${{ env.DOCKER_USERNAME }}/infisical:latest

          # Logs
          docker ps -a
          echo "===== POSTGRES LOGS ====="
          docker logs infisical-db
          echo "===== INFISICAL LOGS ====="
          docker logs infisical-backend

          # Cleanup
          docker image prune --all --force
          rm -f /root/infisical.env
          unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_REGION
          EOF
