name: CI/CD - Build, Push & Deploy Infisical

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  BUILD_NUMBER: ${{ github.run_number }}
  EC2_IP: 15.156.219.253
  SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ca-central-1
  SECRET_ARN: arn:aws:secretsmanager:ca-central-1:659666453025:secret:infisical-secret-NGmqNX

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Pull base images
        run: docker compose -f docker-compose.prod.yml pull

      - name: Tag and Push Backend Image
        run: |
          docker tag infisical/infisical:latest-postgres ${{ env.DOCKER_USERNAME }}/infisical:latest
          docker tag infisical/infisical:latest-postgres ${{ env.DOCKER_USERNAME }}/infisical:${{ env.BUILD_NUMBER }}
          docker push ${{ env.DOCKER_USERNAME }}/infisical:latest
          docker push ${{ env.DOCKER_USERNAME }}/infisical:${{ env.BUILD_NUMBER }}

      - name: Tag and Push Postgres Image
        run: |
          docker tag postgres:14-alpine ${{ env.DOCKER_USERNAME }}/postgres:latest
          docker tag postgres:14-alpine ${{ env.DOCKER_USERNAME }}/postgres:${{ env.BUILD_NUMBER }}
          docker push ${{ env.DOCKER_USERNAME }}/postgres:latest
          docker push ${{ env.DOCKER_USERNAME }}/postgres:${{ env.BUILD_NUMBER }}

      - name: Tag and Push Redis Image
        run: |
          docker tag redis ${{ env.DOCKER_USERNAME }}/redis-image:latest
          docker tag redis ${{ env.DOCKER_USERNAME }}/redis-image:${{ env.BUILD_NUMBER }}
          docker push ${{ env.DOCKER_USERNAME }}/redis-image:latest
          docker push ${{ env.DOCKER_USERNAME }}/redis-image:${{ env.BUILD_NUMBER }}

  deploy:
    name: CD - Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Retrieve Secrets from AWS Secrets Manager
        id: get-secrets
        run: |
          SECRET_STRING=$(aws secretsmanager get-secret-value --secret-id ${{ env.SECRET_ARN }} --query SecretString --output text)
          echo "::add-mask::$SECRET_STRING"
          echo "SECRET_STRING=$SECRET_STRING" >> $GITHUB_ENV

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << 'EOF'
          set -e

          echo ">>> Installing AWS CLI v2 if not present"
          if ! command -v aws &> /dev/null; then
            apt-get update
            apt-get install -y unzip curl jq docker.io
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi

          echo ">>> Setting AWS credentials"
          export AWS_ACCESS_KEY_ID="${{ env.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ env.AWS_SECRET_ACCESS_KEY }}"
          export AWS_REGION="${{ env.AWS_REGION }}"

          echo ">>> Retrieving secrets from AWS Secrets Manager"
          SECRET_JSON=\$(aws secretsmanager get-secret-value --secret-id ${{ env.SECRET_ARN }} --query SecretString --output text)

          ENCRYPTION_KEY=\$(echo "\$SECRET_JSON" | jq -r '.ENCRYPTION_KEY')
          AUTH_SECRET=\$(echo "\$SECRET_JSON" | jq -r '.AUTH_SECRET')
          POSTGRES_PASSWORD=\$(echo "\$SECRET_JSON" | jq -r '.POSTGRES_PASSWORD')
          POSTGRES_USER=\$(echo "\$SECRET_JSON" | jq -r '.POSTGRES_USER')
          POSTGRES_DB=\$(echo "\$SECRET_JSON" | jq -r '.POSTGRES_DB')
          SITE_URL=\$(echo "\$SECRET_JSON" | jq -r '.SITE_URL')

          echo ">>> Writing environment file"
          cat > /root/infisical.env << EOL
          ENCRYPTION_KEY=\$ENCRYPTION_KEY
          AUTH_SECRET=\$AUTH_SECRET
          POSTGRES_PASSWORD=\$POSTGRES_PASSWORD
          POSTGRES_USER=\$POSTGRES_USER
          POSTGRES_DB=\$POSTGRES_DB
          DB_CONNECTION_URI=postgres://\$POSTGRES_USER:\$POSTGRES_PASSWORD@infisical-db:5432/\$POSTGRES_DB
          REDIS_URL=redis://infisical-dev-redis:6379
          SITE_URL=\$SITE_URL
          EOL

          echo ">>> Cleaning existing containers"
          docker stop infisical-backend infisical-db infisical-dev-redis || true
          docker rm infisical-backend infisical-db infisical-dev-redis || true

          echo ">>> Pulling new Docker images"
          docker pull ${{ env.DOCKER_USERNAME }}/infisical:latest
          docker pull ${{ env.DOCKER_USERNAME }}/postgres:latest
          docker pull ${{ env.DOCKER_USERNAME }}/redis-image:latest

          echo ">>> Creating Docker network and volume"
          docker network create infisical-network || true
          docker volume create postgres_data || true

          echo ">>> Running Postgres container"
          docker run -d --name infisical-db \
            --network infisical-network \
            -p 5432:5432 \
            -v postgres_data:/var/lib/postgresql/data \
            -e POSTGRES_USER=\$POSTGRES_USER \
            -e POSTGRES_PASSWORD=\$POSTGRES_PASSWORD \
            -e POSTGRES_DB=\$POSTGRES_DB \
            --restart unless-stopped \
            ${{ env.DOCKER_USERNAME }}/postgres:latest

          echo ">>> Waiting for DB to be ready"
          sleep 10

          echo ">>> Running Redis container"
          docker run -d --name infisical-dev-redis \
            --network infisical-network \
            -p 6379:6379 \
            --restart unless-stopped \
            ${{ env.DOCKER_USERNAME }}/redis-image:latest

          echo ">>> Running Backend container"
          docker run -d --name infisical-backend \
            --network infisical-network \
            -p 80:8080 \
            --env-file /root/infisical.env \
            --restart unless-stopped \
            ${{ env.DOCKER_USERNAME }}/infisical:latest

          echo ">>> Checking container status"
          docker ps -a

          echo ">>> Printing logs"
          docker logs infisical-db || true
          docker logs infisical-backend || true

          echo ">>> Cleaning up unused images"
          docker image prune --force

          echo ">>> Cleaning up credentials and env"
          rm -f /root/infisical.env
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_REGION
          EOF
